### PR TITLE
Generate Decimals using Decimal.js

### PR DESCRIPTION
**Pull request by SSmietana**
Updates Decimal generation to match [Prisma's use of the Decimal.js library](https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types#working-with-decimal)

### CODE REVIEW

**Comment by luisrudge** [comment]
thanks for the PR. can you elaborate a bit more on why this change is needed?

**Comment by SSmietana** [comment]
@luisrudge prisma uses Decimal.js to represent `Decimal` db types. The current implementation generates a hexadecimal value, which results in a Type Error due to this mismatch between the generated hexadecimal string value, and the expected Decimal value.

**Comment by SSmietana** [comment]
@luisrudge any update on this, will this PR go forward?

**Comment by luisrudge** [comment]
Yes, I'm planning to merge it this week. I just wanna play around a bit. Not a big fan of adding the dependency since it might conflict with other projects already using this... 

Also, this would be an issue with BigInt as well, since we're using `faker.datatypes.int()` instead of `BigInt`. 

In the meantime, can you please make sure you update bun's lockfile? thanks!

**Comment by luisrudge** [comment]
released in https://github.com/luisrudge/prisma-generator-fake-data/releases/tag/v0.14.0

**Pull request merged**
